/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#if ENABLE(MEDIA_STREAM)

#include "JSMediaStreamTrack.h"

#include "Event.h"
#include "EventListener.h"
#include "ExceptionCode.h"
#include "JSDOMBinding.h"
#include "JSEvent.h"
#include "JSEventListener.h"
#include "KURL.h"
#include "MediaStreamTrack.h"
#include <runtime/Error.h>
#include <runtime/JSString.h>
#include <wtf/GetPtr.h>

using namespace JSC;

namespace WebCore {

/* Hash table */

static const HashTableValue JSMediaStreamTrackTableValues[] =
{
    { "kind", DontDelete | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackKind), (intptr_t)0, NoIntrinsic },
    { "id", DontDelete | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackId), (intptr_t)0, NoIntrinsic },
    { "label", DontDelete | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackLabel), (intptr_t)0, NoIntrinsic },
    { "enabled", DontDelete, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackEnabled), (intptr_t)setJSMediaStreamTrackEnabled, NoIntrinsic },
    { "readyState", DontDelete | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackReadyState), (intptr_t)0, NoIntrinsic },
    { "onmute", DontDelete, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackOnmute), (intptr_t)setJSMediaStreamTrackOnmute, NoIntrinsic },
    { "onunmute", DontDelete, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackOnunmute), (intptr_t)setJSMediaStreamTrackOnunmute, NoIntrinsic },
    { "onended", DontDelete, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsMediaStreamTrackOnended), (intptr_t)setJSMediaStreamTrackOnended, NoIntrinsic },
    { 0, 0, 0, 0, NoIntrinsic }
};

static const HashTable JSMediaStreamTrackTable = { 17, 15, JSMediaStreamTrackTableValues, 0 };
/* Hash table for prototype */

static const HashTableValue JSMediaStreamTrackPrototypeTableValues[] =
{
    { "addEventListener", DontDelete | JSC::Function, (intptr_t)static_cast<NativeFunction>(jsMediaStreamTrackPrototypeFunctionAddEventListener), (intptr_t)2, NoIntrinsic },
    { "removeEventListener", DontDelete | JSC::Function, (intptr_t)static_cast<NativeFunction>(jsMediaStreamTrackPrototypeFunctionRemoveEventListener), (intptr_t)2, NoIntrinsic },
    { "dispatchEvent", DontDelete | JSC::Function, (intptr_t)static_cast<NativeFunction>(jsMediaStreamTrackPrototypeFunctionDispatchEvent), (intptr_t)1, NoIntrinsic },
    { 0, 0, 0, 0, NoIntrinsic }
};

static const HashTable JSMediaStreamTrackPrototypeTable = { 8, 7, JSMediaStreamTrackPrototypeTableValues, 0 };
const ClassInfo JSMediaStreamTrackPrototype::s_info = { "MediaStreamTrackPrototype", &Base::s_info, &JSMediaStreamTrackPrototypeTable, 0, CREATE_METHOD_TABLE(JSMediaStreamTrackPrototype) };

JSObject* JSMediaStreamTrackPrototype::self(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSMediaStreamTrack>(exec, globalObject);
}

bool JSMediaStreamTrackPrototype::getOwnPropertySlot(JSObject* object, ExecState* exec, PropertyName propertyName, PropertySlot& slot)
{
    JSMediaStreamTrackPrototype* thisObject = jsCast<JSMediaStreamTrackPrototype*>(object);
    return getStaticFunctionSlot<JSObject>(exec, &JSMediaStreamTrackPrototypeTable, thisObject, propertyName, slot);
}

const ClassInfo JSMediaStreamTrack::s_info = { "MediaStreamTrack", &Base::s_info, &JSMediaStreamTrackTable, 0 , CREATE_METHOD_TABLE(JSMediaStreamTrack) };

JSMediaStreamTrack::JSMediaStreamTrack(Structure* structure, JSDOMGlobalObject* globalObject, PassRefPtr<MediaStreamTrack> impl)
    : JSDOMWrapper(structure, globalObject)
    , m_impl(impl.leakRef())
{
}

void JSMediaStreamTrack::finishCreation(VM& vm)
{
    Base::finishCreation(vm);
    ASSERT(inherits(info()));
}

JSObject* JSMediaStreamTrack::createPrototype(ExecState* exec, JSGlobalObject* globalObject)
{
    return JSMediaStreamTrackPrototype::create(exec->vm(), globalObject, JSMediaStreamTrackPrototype::createStructure(globalObject->vm(), globalObject, globalObject->objectPrototype()));
}

void JSMediaStreamTrack::destroy(JSC::JSCell* cell)
{
    JSMediaStreamTrack* thisObject = static_cast<JSMediaStreamTrack*>(cell);
    thisObject->JSMediaStreamTrack::~JSMediaStreamTrack();
}

JSMediaStreamTrack::~JSMediaStreamTrack()
{
    releaseImplIfNotNull();
}

bool JSMediaStreamTrack::getOwnPropertySlot(JSObject* object, ExecState* exec, PropertyName propertyName, PropertySlot& slot)
{
    JSMediaStreamTrack* thisObject = jsCast<JSMediaStreamTrack*>(object);
    ASSERT_GC_OBJECT_INHERITS(thisObject, info());
    return getStaticValueSlot<JSMediaStreamTrack, Base>(exec, &JSMediaStreamTrackTable, thisObject, propertyName, slot);
}

JSValue jsMediaStreamTrackKind(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    JSValue result = jsStringWithCache(exec, impl->kind());
    return result;
}


JSValue jsMediaStreamTrackId(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    JSValue result = jsStringWithCache(exec, impl->id());
    return result;
}


JSValue jsMediaStreamTrackLabel(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    JSValue result = jsStringWithCache(exec, impl->label());
    return result;
}


JSValue jsMediaStreamTrackEnabled(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    JSValue result = jsBoolean(impl->enabled());
    return result;
}


JSValue jsMediaStreamTrackReadyState(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    JSValue result = jsStringWithCache(exec, impl->readyState());
    return result;
}


JSValue jsMediaStreamTrackOnmute(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    if (EventListener* listener = impl->onmute()) {
        if (const JSEventListener* jsListener = JSEventListener::cast(listener)) {
            if (JSObject* jsFunction = jsListener->jsFunction(impl->scriptExecutionContext()))
                return jsFunction;
        }
    }
    return jsNull();
}


JSValue jsMediaStreamTrackOnunmute(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    if (EventListener* listener = impl->onunmute()) {
        if (const JSEventListener* jsListener = JSEventListener::cast(listener)) {
            if (JSObject* jsFunction = jsListener->jsFunction(impl->scriptExecutionContext()))
                return jsFunction;
        }
    }
    return jsNull();
}


JSValue jsMediaStreamTrackOnended(ExecState* exec, JSValue slotBase, PropertyName)
{
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    if (EventListener* listener = impl->onended()) {
        if (const JSEventListener* jsListener = JSEventListener::cast(listener)) {
            if (JSObject* jsFunction = jsListener->jsFunction(impl->scriptExecutionContext()))
                return jsFunction;
        }
    }
    return jsNull();
}


void JSMediaStreamTrack::put(JSCell* cell, ExecState* exec, PropertyName propertyName, JSValue value, PutPropertySlot& slot)
{
    JSMediaStreamTrack* thisObject = jsCast<JSMediaStreamTrack*>(cell);
    ASSERT_GC_OBJECT_INHERITS(thisObject, info());
    lookupPut<JSMediaStreamTrack, Base>(exec, propertyName, value, &JSMediaStreamTrackTable, thisObject, slot);
}

void setJSMediaStreamTrackEnabled(ExecState* exec, JSObject* thisObject, JSValue value)
{
    UNUSED_PARAM(exec);
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(thisObject);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    bool nativeValue(value.toBoolean(exec));
    if (exec->hadException())
        return;
    impl->setEnabled(nativeValue);
}


void setJSMediaStreamTrackOnmute(ExecState* exec, JSObject* thisObject, JSValue value)
{
    UNUSED_PARAM(exec);
    UNUSED_PARAM(exec);
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(thisObject);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    impl->setOnmute(createJSAttributeEventListener(exec, value, thisObject));
}


void setJSMediaStreamTrackOnunmute(ExecState* exec, JSObject* thisObject, JSValue value)
{
    UNUSED_PARAM(exec);
    UNUSED_PARAM(exec);
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(thisObject);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    impl->setOnunmute(createJSAttributeEventListener(exec, value, thisObject));
}


void setJSMediaStreamTrackOnended(ExecState* exec, JSObject* thisObject, JSValue value)
{
    UNUSED_PARAM(exec);
    UNUSED_PARAM(exec);
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(thisObject);
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    impl->setOnended(createJSAttributeEventListener(exec, value, thisObject));
}


EncodedJSValue JSC_HOST_CALL jsMediaStreamTrackPrototypeFunctionAddEventListener(ExecState* exec)
{
    JSValue thisValue = exec->hostThisValue();
    if (!thisValue.inherits(JSMediaStreamTrack::info()))
        return throwVMTypeError(exec);
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(thisValue));
    ASSERT_GC_OBJECT_INHERITS(castedThis, JSMediaStreamTrack::info());
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    JSValue listener = exec->argument(1);
    if (!listener.isObject())
        return JSValue::encode(jsUndefined());
    impl->addEventListener(exec->argument(0).toString(exec)->value(exec), JSEventListener::create(asObject(listener), castedThis, false, currentWorld(exec)), exec->argument(2).toBoolean(exec));
    return JSValue::encode(jsUndefined());
}

EncodedJSValue JSC_HOST_CALL jsMediaStreamTrackPrototypeFunctionRemoveEventListener(ExecState* exec)
{
    JSValue thisValue = exec->hostThisValue();
    if (!thisValue.inherits(JSMediaStreamTrack::info()))
        return throwVMTypeError(exec);
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(thisValue));
    ASSERT_GC_OBJECT_INHERITS(castedThis, JSMediaStreamTrack::info());
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    JSValue listener = exec->argument(1);
    if (!listener.isObject())
        return JSValue::encode(jsUndefined());
    impl->removeEventListener(exec->argument(0).toString(exec)->value(exec), JSEventListener::create(asObject(listener), castedThis, false, currentWorld(exec)).get(), exec->argument(2).toBoolean(exec));
    return JSValue::encode(jsUndefined());
}

EncodedJSValue JSC_HOST_CALL jsMediaStreamTrackPrototypeFunctionDispatchEvent(ExecState* exec)
{
    JSValue thisValue = exec->hostThisValue();
    if (!thisValue.inherits(JSMediaStreamTrack::info()))
        return throwVMTypeError(exec);
    JSMediaStreamTrack* castedThis = jsCast<JSMediaStreamTrack*>(asObject(thisValue));
    ASSERT_GC_OBJECT_INHERITS(castedThis, JSMediaStreamTrack::info());
    MediaStreamTrack* impl = static_cast<MediaStreamTrack*>(castedThis->impl());
    if (exec->argumentCount() < 1)
        return throwVMError(exec, createNotEnoughArgumentsError(exec));
    ExceptionCode ec = 0;
    Event* event(toEvent(exec->argument(0)));
    if (exec->hadException())
        return JSValue::encode(jsUndefined());

    JSC::JSValue result = jsBoolean(impl->dispatchEvent(event, ec));
    setDOMException(exec, ec);
    return JSValue::encode(result);
}

void JSMediaStreamTrack::visitChildren(JSCell* cell, SlotVisitor& visitor)
{
    JSMediaStreamTrack* thisObject = jsCast<JSMediaStreamTrack*>(cell);
    ASSERT_GC_OBJECT_INHERITS(thisObject, info());
    COMPILE_ASSERT(StructureFlags & OverridesVisitChildren, OverridesVisitChildrenWithoutSettingFlag);
    ASSERT(thisObject->structure()->typeInfo().overridesVisitChildren());
    Base::visitChildren(thisObject, visitor);
    thisObject->impl()->visitJSEventListeners(visitor);
}

static inline bool isObservable(JSMediaStreamTrack* jsMediaStreamTrack)
{
    if (jsMediaStreamTrack->hasCustomProperties())
        return true;
    if (jsMediaStreamTrack->impl()->hasEventListeners())
        return true;
    return false;
}

bool JSMediaStreamTrackOwner::isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown> handle, void*, SlotVisitor& visitor)
{
    JSMediaStreamTrack* jsMediaStreamTrack = jsCast<JSMediaStreamTrack*>(handle.get().asCell());
    if (jsMediaStreamTrack->impl()->hasPendingActivity())
        return true;
    if (jsMediaStreamTrack->impl()->isFiringEventListeners())
        return true;
    if (!isObservable(jsMediaStreamTrack))
        return false;
    UNUSED_PARAM(visitor);
    return false;
}

void JSMediaStreamTrackOwner::finalize(JSC::Handle<JSC::Unknown> handle, void* context)
{
    JSMediaStreamTrack* jsMediaStreamTrack = jsCast<JSMediaStreamTrack*>(handle.get().asCell());
    DOMWrapperWorld* world = static_cast<DOMWrapperWorld*>(context);
    uncacheWrapper(world, jsMediaStreamTrack->impl(), jsMediaStreamTrack);
    jsMediaStreamTrack->releaseImpl();
}

#if ENABLE(BINDING_INTEGRITY)
#if PLATFORM(WIN)
#pragma warning(disable: 4483)
extern "C" { extern void (*const __identifier("??_7MediaStreamTrack@WebCore@@6B@")[])(); }
#else
extern "C" { extern void* _ZTVN7WebCore16MediaStreamTrackE[]; }
#endif
#endif
JSC::JSValue toJS(JSC::ExecState* exec, JSDOMGlobalObject* globalObject, MediaStreamTrack* impl)
{
    if (!impl)
        return jsNull();
    if (JSValue result = getExistingWrapper<JSMediaStreamTrack>(exec, impl))
        return result;

#if ENABLE(BINDING_INTEGRITY)
    void* actualVTablePointer = *(reinterpret_cast<void**>(impl));
#if PLATFORM(WIN)
    void* expectedVTablePointer = reinterpret_cast<void*>(__identifier("??_7MediaStreamTrack@WebCore@@6B@"));
#else
    void* expectedVTablePointer = &_ZTVN7WebCore16MediaStreamTrackE[2];
#if COMPILER(CLANG)
    // If this fails MediaStreamTrack does not have a vtable, so you need to add the
    // ImplementationLacksVTable attribute to the interface definition
    COMPILE_ASSERT(__is_polymorphic(MediaStreamTrack), MediaStreamTrack_is_not_polymorphic);
#endif
#endif
    // If you hit this assertion you either have a use after free bug, or
    // MediaStreamTrack has subclasses. If MediaStreamTrack has subclasses that get passed
    // to toJS() we currently require MediaStreamTrack you to opt out of binding hardening
    // by adding the SkipVTableValidation attribute to the interface IDL definition
    RELEASE_ASSERT(actualVTablePointer == expectedVTablePointer);
#endif
    ReportMemoryCost<MediaStreamTrack>::reportMemoryCost(exec, impl);
    return createNewWrapper<JSMediaStreamTrack>(exec, globalObject, impl);
}

MediaStreamTrack* toMediaStreamTrack(JSC::JSValue value)
{
    return value.inherits(JSMediaStreamTrack::info()) ? jsCast<JSMediaStreamTrack*>(asObject(value))->impl() : 0;
}

}

#endif // ENABLE(MEDIA_STREAM)
